platformName: Android
platforVersion: 5.1.1
deviceName: 127.0.0.1:62001
appname: kaoyan3.1.0.apk
noReset: False
appPackage: com.tal.kaoyan
appActivity: com.tal.kaoyan.ui.activity.SplashActivity
ip: 127.0.0.1
port: 4723